# Generated by Django 5.0.4 on 2024-04-25 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_music_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='music',
            name='rating',
        ),
        migrations.AddField(
            model_name='music',
            name='image',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
    ]
