# Generated by Django 5.0.4 on 2024-05-28 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_trackrating_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='spotify_id',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
